repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1 # Use the latest version
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
    - repo: https://github.com/psf/black
      rev: 22.3.0 # Use the latest version
      hooks:
          - id: black
            language_version: python3
